const byId = (id) => document.getElementById(id);
export const [
  keyView,
  chatView,
  keyInput,
  baseUrlInput,
  modelInput,
  apiTypeSelect,
  themeSelect,
  keyStatus,
  openSettings,
  saveKey,
  cancelSettings,
  messagesEl,
  promptEl,
  sendButton,
  sendWithPageButton,
  clearButton,
  statusEl,
] = [
  "key-view",
  "chat-view",
  "api-key-input",
  "base-url-input",
  "model-input",
  "api-type-select",
  "theme-select",
  "key-status",
  "open-settings",
  "save-key",
  "cancel-settings",
  "messages",
  "prompt",
  "send",
  "send-with-page",
  "clear",
  "status",
].map(byId);
